export const CHAT_ACTIONS = {
  GET_CONTACTS_REQUEST: 'GET_CONTACTS_REQUEST',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACTS_FAILURE: 'GET_CONTACTS_FAILURE',

  GET_CONVERSATIONS_REQUEST: 'GET_CONVERSATIONS_REQUEST',
  GET_CONVERSATIONS_SUCCESS: 'GET_CONVERSATIONS_SUCCESS',
  GET_CONVERSATIONS_FAILURE: 'GET_CONVERSATIONS_FAILURE',

  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',

  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',

  SELECT_CONVERSATION: 'SELECT_CONVERSATION',
  
  // Socket related actions
  SOCKET_INIT: 'SOCKET_INIT',
  SOCKET_MESSAGE_RECEIVED: 'SOCKET_MESSAGE_RECEIVED',
  SOCKET_CONVERSATION_UPDATED: 'SOCKET_CONVERSATION_UPDATED',
  SOCKET_TYPING: 'SOCKET_TYPING',
  SOCKET_READ_RECEIPT: 'SOCKET_READ_RECEIPT',
};