import React from "react";
import { Routes, Route, Navigate, Outlet } from "react-router-dom";
import { Helmet } from "react-helmet";

/* Import CSS files */
import "./globals.css";
import 'rc-slider/assets/index.css';

/* Import CSS từ thư mục assets */
import "./assets/css/aos.css";
import "./assets/css/bootstrap.min.css";
import "./assets/css/flaticon.min.css";
import "./assets/css/fontawesome-5.14.0.min.css";
import "./assets/css/magnific-popup.min.css";
import "./assets/css/nice-select.min.css";
import "./assets/css/slick.min.css";
import "./assets/css/style.css"

/* Import your page components here */
import About from './pages/About';
import Contact from './pages/Contact';
import Destination2 from './pages/Destination2';
import Home from './pages/Home';
import Home2 from './pages/Home2';
import Home3 from './pages/Home3';
import NotFound from './pages/NotFound';
import Tour_details from './pages/Tour_details';
import Tour_list from './pages/Tour_list';
import Tour_guide from './pages/Tour_guide';
import Tour_sidebar from './pages/Tour_sidebar';
import ReveloLayout from "./components/layout/ReveloLayout";
/* Auth user */
import Auth from "./pages/Auth/Auth";
import ForgotPassword from "./pages/Auth/ForgotPassword";
import AccountVerification from "./pages/Auth/AccountVerification";
import ResetPassword from "./components/ResetPassword";


import { useSelector } from 'react-redux'
import { selectCurrentUser } from '~/redux/user/userSlice'
import Settings from '~/pages/Settings/Settings'

const ProtectedRoute = ({ user }) => {
  if (!user) return <Navigate to='/login' replace={true} />
  return <Outlet />
}
function App() {
  const currentUser = useSelector(selectCurrentUser)

  return (
    <>
      <Helmet>
        <title>KTTravel - Travel & Tour Booking</title>
        <meta
          name="description"
          content="Generated by KTTravel - Travel & Tour Booking"
        />
      </Helmet>

      <Routes>
        {/* Redirect Route*/}
        <Route path="/" element={
          <ReveloLayout header={1} footer={1}>
            <Home />
          </ReveloLayout>
        } />

        {/* Authentication */}
        <Route path="/login" element={
          <ReveloLayout header={1} footer={1}>
            <Auth />
          </ReveloLayout>

        } />

        <Route path="/register" element={
          <ReveloLayout header={1} footer={1}>
            <Auth />
          </ReveloLayout>
        } />

        <Route path='/account/verification' element={
          <ReveloLayout header={1} footer={1}>
            <AccountVerification />
          </ReveloLayout>
        }
        />

        <Route path="/forgot-password" element={
          <ReveloLayout header={1} footer={1}>
            <ForgotPassword />
          </ReveloLayout>
        }
        />

        <Route path="/account/reset-password" element={
          <ReveloLayout header={1} footer={1}>
            <ResetPassword />
          </ReveloLayout>
        }
        />
        {/* ProtectedRoute Routes */}
        < Route element={<ProtectedRoute user={currentUser} />}>
          {/* <Outlet /> của react-router-dom sẽ chạy vào các child route trong này */}


          {/* User setting */}
          <Route path='/settings/account' element={
            <ReveloLayout header={1} footer={1}>
              <Settings />
            </ReveloLayout>} />
          <Route path='/settings/security' element={
            <ReveloLayout header={1} footer={1}>
              <Settings />
            </ReveloLayout>} />

        </Route>


        <Route path="/home2" element={<Home2 />} />
        <Route path="/home3" element={<Home3 />} />

        <Route path="/about" element={
          <ReveloLayout >
            <About />
          </ReveloLayout>

        } />

        <Route path="/tour" element={
          <ReveloLayout>
            <Tour_list />
          </ReveloLayout>
        } />
        <Route path="/tour_guide" element={<Tour_guide />} />

        <Route path="/contact" element={
          <ReveloLayout insta>
            <Contact />
          </ReveloLayout>
        } />


        <Route path="/destination" element={
          <ReveloLayout>
            <Destination2 />
          </ReveloLayout>
        } />


        <Route path="/tour_sidebar" element={<Tour_sidebar />} />




        <Route path="*" element={<NotFound />} />
      </Routes>
    </>
  );
}

export default App;