import React from "react";
import { Routes, Route } from "react-router-dom";
import { Helmet } from "react-helmet";

// Import CSS files
import "./globals.css";
import 'rc-slider/assets/index.css';

// Import CSS từ thư mục assets
import "./assets/css/aos.css";
import "./assets/css/bootstrap.min.css";
import "./assets/css/flaticon.min.css";
import "./assets/css/fontawesome-5.14.0.min.css";
import "./assets/css/magnific-popup.min.css";
import "./assets/css/nice-select.min.css";
import "./assets/css/slick.min.css";
import "./assets/css/style.css"; // File CSS chính của bạn

// Import your page components here
import About from './pages/About';
import Blog_details from './pages/Blog_details';
import Blog from './pages/Blog';
import Contact from './pages/Contact';
import Destination2 from './pages/Destination2';
import Faqs from './pages/Faqs';
import Gellery_grid from './pages/Gellery_grid';
import Gellery_slider from './pages/Gellery_slider';
import Home from './pages/Home';
import Home2 from './pages/Home2';
import Home3 from './pages/Home3';
import NotFound from './pages/NotFound';
import Pricing from './pages/Pricing';
import Product_details from './pages/Product_details';
import Shop from './pages/Shop';
import Tour_details from './pages/Tour_details';
import Tour_grid from './pages/Tour_grid';
import Tour_guide from './pages/Tour_guide';
import Tour_sidebar from './pages/Tour_sidebar';
import ReveloLayout from "./components/layout/ReveloLayout";
import Footer1 from "./components/layout/Footer/Footer1";
import Login from "./components/layout/Header/Login";
import Register from "./components/layout/Header/Register";
import ForgotPassword from "./components/layout/Header/ForgotPassword";

function App() {
  return (
    <>
      <Helmet>
        <title>KTTravel - Travel & Tour Booking</title>
        <meta
          name="description"
          content="Generated by KTTravel - Travel & Tour Booking"
        />
      </Helmet>

      <Routes>
        <Route path="/" element={
          <ReveloLayout header={1} footer={1}>
            <Home />
          </ReveloLayout>


        } />

        <Route path="/login" element={
          <ReveloLayout header={1} footer={1}>
            <Login />
          </ReveloLayout>

        } />
        <Route path="/forgot-password" element={
          <ReveloLayout header={1} footer={1}>
            <ForgotPassword />
          </ReveloLayout>

        } />
        <Route path="/register" element={
          <ReveloLayout header={1} footer={1}>
            <Register />
          </ReveloLayout>

        } />



        <Route path="/home2" element={<Home2 />} />
        <Route path="/home3" element={<Home3 />} />

        <Route path="/about" element={
          <ReveloLayout >
            <About />
          </ReveloLayout>

        } />


        <Route path="/blog" element={<Blog />} />
        <Route path="/blog_details" element={<Blog_details />} />
        <Route path="/contact" element={<Contact />} />
        <Route path="/destination" element={<Destination2 />} />
        <Route path="/faqs" element={<Faqs />} />
        <Route path="/gellery_grid" element={<Gellery_grid />} />
        <Route path="/gellery_slider" element={<Gellery_slider />} />
        <Route path="/pricing" element={<Pricing />} />
        <Route path="/product_details" element={<Product_details />} />
        <Route path="/shop" element={<Shop />} />
        <Route path="/tour-list" element={<Tour_details />} />
        <Route path="/tour_guide" element={<Tour_guide />} />
        <Route path="/tour_sidebar" element={<Tour_sidebar />} />
        <Route path="*" element={<NotFound />} />
      </Routes>
    </>
  );
}

export default App;